"""add prescription item model

Revision ID: c4ff53c23f75
Revises: e4e81ecaaf32
Create Date: 2025-07-08 20:26:27.006330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c4ff53c23f75'
down_revision: Union[str, None] = 'e4e81ecaaf32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prescription_items',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('prescription_id', sa.Uuid(), nullable=False),
    sa.Column('medication_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('dosage', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('frequency', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('quantity', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('duration', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('instructions', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('prescriptions_medication_id_fkey', 'prescriptions', type_='foreignkey')
    op.drop_column('prescriptions', 'instructions')
    op.drop_column('prescriptions', 'dosage')
    op.drop_column('prescriptions', 'medication_id')
    op.drop_column('prescriptions', 'frequency')
    op.drop_column('prescriptions', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prescriptions', sa.Column('quantity', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('prescriptions', sa.Column('frequency', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('prescriptions', sa.Column('medication_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('prescriptions', sa.Column('dosage', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('prescriptions', sa.Column('instructions', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.create_foreign_key('prescriptions_medication_id_fkey', 'prescriptions', 'medications', ['medication_id'], ['id'])
    op.drop_table('prescription_items')
    # ### end Alembic commands ###
