"""Add status to prescription_pdfs

Revision ID: e4e81ecaaf32
Revises: 5148edfdf886
Create Date: 2025-07-08 01:51:12.771748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e4e81ecaaf32'
down_revision: Union[str, None] = '5148edfdf886'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prescription_pdfs', sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'COMPLETED', 'DISCONTINUED', name='prescriptionstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prescription_pdfs', 'status')
    # ### end Alembic commands ###
